name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get install -y --no-install-recommends gcc make autoconf libgtk2.0-dev libxml2-dev
    - name: Build
      run: ./ROX-Filer/AppRun --compile
